const albumElements={output:{albumCiv:"albumCiv",album:"album",albumType:"albumType",albumHeaderName:"albumHeaderName",albumImage:"albumImage",albumName:"albumName",albumOther:"albumOther",albumGlyphs:"albumGlyphs",albumDiscoverer:"albumDiscoverer",albumText:"albumText",albumDesc:"albumDesc"}};function albumLink(e){e.style.pointerEvents="none";var t="function"==typeof albumLinkGen?albumLinkGen():pageData.catalogue||(console.warn("No wiki page provided. Add the function `albumLinkGen()` to your code or define a catalog in the `pageData.catalogue` property!"),void(e.style.pointerEvents=""));t&&assignLink(e,wikiLink+t)}function albumItemType(){var e="function"==typeof albumItemTypeExternal?albumItemTypeExternal():pageData.type;globalElements.output.album.innerText=e}function albumDesc(){var e="function"==typeof albumDescExternal?albumDescExternal():"";globalElements.output.albumDesc.innerText=e}function albumDiscoverer(){var e,t="function"==typeof albumDiscovererExternal?albumDiscovererExternal():(e=pageData.discovered,(t=pageData.discoveredlink)?"wiki="+t:"discoverer="+e);globalElements.output.albumDiscoverer.innerText=t}function albumCiv(){var e="function"==typeof albumCivExternal?albumCivExternal():pageData.civShort;globalElements.output.albumCiv.innerText=e}function albumName(){var e="function"==typeof albumNameExternal?albumNameExternal():pageData.name;globalElements.output.albumName.innerText=e}function albumOther(){var e="function"==typeof albumOtherExternal?albumOtherExternal():"";globalElements.output.albumOther.innerText=e}function albumType(){var e="function"==typeof albumTypeExternal?albumTypeExternal():"";globalElements.output.albumType.innerText=e}function albumFunctions(){albumCiv(),albumDiscoverer(),albumName(),albumOther(),albumType(),albumItemType(),albumDesc()}(()=>{globalElements.output.albumEntry&&(globalElements.output.albumEntry.innerHTML=`<h3 class="title is-5 has-text-left has-text-weight-bold mb-2"><output id="albumCiv"></output>
<output id="album" name="type"></output> <output id="albumType"></output> entry for <output id='albumHeaderName' name="name"></output>:
</h3>
<div id="albumText" class="wikiText">
| {{album| file=<output name="image" id="albumImage"></output> | name=[[<output id="albumName"></output>]]
| other=<output id="albumOther"></output> | glyph=<output id='albumGlyphs' name="portalglyphs"></output> |
<output id="albumDiscoverer"></output>}} <output id="albumDesc"></output>
</div>`),globalElements.output.albumActions&&(globalElements.output.albumActions.innerHTML=`<button id="albumBtn" class="button is-outlined is-primary"
onclick="copyCode(this, 'albumText')">
Copy album wikicode
</button>
<a class="button is-outlined is-primary" id="albumLink"
onclick="albumLink(this)">
Open Album
</a>`),updateGlobalElements(albumElements);assignElementFunctions({civ:["albumCiv()",null,!0]})})();