
/**
 * @fileoverview Provides data for creature datalists
 */
const creatureDatalists = {
	dietData: [
		'[[Star Bramble]]',
		'[[Echinocactus]]',
		'[[Solar Vine]]',
		'[[Frostwort]]',
		'[[Fungal Cluster]]',
		'[[Gamma Weed]]',
		'[[Mordite Root]]',
		'Nitrous Oxide',
		'[[Cadmium]]',
		'[[Emeril]]',
		'[[Indium]]',
		'[[Kelp Sac]]',
		'[[Condensed Carbon]]',
		'Vegetation',
		'Foliage',
		'Small trees',
		'Rotting fruit',
		'Fresh leaves',
		'Plant roots',
		'Digs for tubers',
		'Grass',
		'Foraged nuts',
		'Collects seeds',
		'Nibbles at shoots',
		'Tall grasses',
		'[[Cave Marrow|Cave marrow]]',
		'[[Mordite Root|Mordite roots]]',
		'[[Faecium]]',
		'[[Coprite]]',
		'Well-Matured Dung',
		'Mostly rocks',
		'[[Di-hydrogen]] crystals',
		'Processes dirt',
		'Oxide elements',
		'Absorbed nutrients',
		'[[NipNip Buds|NipNip buds]]',
		'[[Gravitino Ball|Gravitino balls]]',
		'Stinging leaves',
		'Algae',
		'Flowers',
		'Petals',
		'Nectar',
		'Pollen',
		'Scavenged scraps',
		'Insects and grubs',
		'Worms',
		'Anything',
		'[[Faecium|Faeces]]',
		'Birds',
		'Scavenged remains',
		'Partially-digested meat',
		'Eggs',
		'Steals from others',
		'[[Venom Urchin]]s',
		'Foraged leftovers',
		'Small animals',
		'Old bones',
		'[[Mordite]]',
		'Carnivorous',
		'Meat-eater',
		'Hypnotises prey',
		'Crunches bones',
		'Blood-drinker',
		'Liquidised organs',
		'Extracts bone marrow',
		'Organs',
		'Raw meat',
		'Flesh-eater',
		'Hypercarnivore',
		'Brain matter',
		'Sinew',
		'Fresh meat',
		'Corpses',
		'Putrefied meat',
		'Cannibal',
		'Offal',
		'Removed hearts',
		'Other carnivores',
		'Large mammals',
		'Flesh chunks',
		'Meat chunks',
		'Coagulated blood',
		'Frozen meat',
		'Boiled meat',
		'Radioactive meat',
		'Toxic meat',
		'Rotten meat',
		'Preserved meat',
		'Fetid meat',
		'Charred meat',
		'Marine snow',
		'Chemosynthesis',
		'Vented minerals',
		'Plankton',
		'Seaweed',
		'Deepwater algae',
		'Small crustaceans',
		'Rotten wood',
		'Decayed plant life',
		'Marine detritus',
		'Algal particulates',
		'Coral',
		'Living sponges',
		'Deepwater spores',
		'Nibbles at moss',
		'Hydrothermal minerals',
		'Water filtration',
		'Drifting plants',
		'Silicates',
		'High in calcium',
		'Water vines',
		'[[Kelp Sac|Kelp sacs]]',
		'Nutritious water weeds',
		'Other fish',
		'Cannibalism',
		'Marine eggs',
		'Turtles',
		'Shellfish',
		'Drifting carcasses',
		'Bones',
		'Hunts squid',
		'Brined organs',
		'Salinated flesh',
		'Brains',
		'Blood',
		'Gelatinous chunks',
		'Wasteflesh',
		'Pure Silicon',
		'Siphoned Data',
		'[[Nanite Cluster]]s',
		'Recycled Heat',
		'Cosmic Rays',
		'Decaying Atoms',
		'Random',
		'Interlopers'
	]
}

export function getGenderData(genus: string = '') {
	const genderData = {
		Mechanoceris: {
      '':'',
			'Asynchronous':'Asíncrono',
			'Circular':'Circular',
			'Electronic':'Electrónico',
			'Mutable':'Mutable',
			'Non-boolean':'No booleano',
			'Non-Euclidean':'No euclidiano',
			'Uninitialised':'No inicializado',
			'Unmeasurable':'Inmensurable',
			'Virtual':'Virtual',
    },
		default: {
      '':'',
			'Alpha':'Alfa',
			'Asymmetric':'Asimétrico',
			'Asymptotic':'Asintótico',
			'Exotic':'Exótico',
			'Female':'Hembra',
			'Indeterminate':'Indeterminado',
			'Male':'Macho',
			'Non-uniform':'No uniforme',
			'None':'Ninguno',
			'Orthogonal':'Ortogonal',
			'Prime':'Principal',
			'Radical':'Radical',
			'Rational':'Racional',
			'Symmetric':'Simétrico',
			'Unknown':'Desconocido',
			'Vectorised':'Vectorizado',
    }
	}

	switch (genus) {
		case 'Mechanoceris':
			return genderData.Mechanoceris;

		case '':
			return genderData;

		default:
			return genderData.default;
	}
}


export default creatureDatalists;
