const creatureDietDatalist: {
  [key: string]: string } = {
  '[[Star Bramble]]':'Zarza estelar',
  '[[Echinocactus]]':'Equinocactus',
  '[[Solar Vine]]':'Vid solar',
  '[[Frostwort]]':'Heliantemo',
  '[[Fungal Cluster]]':'Grupo fúngico',
  '[[Gamma Weed]]':'Hierba gamma',
  '[[Mordite Root]]':'Raíz de mordita',
  'Nitrous Oxide':'Óxido nitroso',
  '[[Cadmium]]':'Cadmio',
  '[[Emeril]]':'Emerilio',
  '[[Indium]]':'Indio',
  '[[Kelp Sac]]':'Saco de algas marinas',
  '[[Condensed Carbon]]':'Carbono condensado',
  'Vegetation':'Vegetación',
  'Foliage':'Follaje',
  'Small trees':'Árboles pequeños',
  'Rotting fruit':'Fruta podrida',
  'Fresh leaves':'Hojas frescas',
  'Plant roots':'Plantas de raíz',
  'Digs for tubers':'Excava en busca de tubérculos',
  'Grass':'Hierba',
  'Foraged nuts':'Busca frutos secos',
  'Collects seeds':'Recoge semillas',
  'Nibbles at shoots':'Mordisquea brotes',
  'Tall grasses':'Hierbas altas',
  '[[Cave Marrow|Cave marrow]]':'Médula de cueva',
  '[[Mordite Root|Mordite roots]]':'Raíces de mordita',
  '[[Faecium]]':'Hecesio',
  '[[Coprite]]':'Coprita',
  'Well-Matured Dung':'Heces maduras',
  'Mostly rocks':'En su mayoría rocas',
  '[[Di-hydrogen]] crystals':'Cristales de dihidrógeno',
  'Processes dirt':'Procesa la suciedad',
  'Oxide elements':'Elementos de óxido',
  'Absorbed nutrients':'Absorción de nutrientes',
  '[[NipNip Buds|NipNip buds]]':'Brotes de NipNip',
  '[[Gravitino Ball|Gravitino balls]]':'Bolas de gravitino',
  'Stinging leaves':'Hojas punzantes',
  'Algae':'Algas',
  'Flowers':'Flores',
  'Petals':'Pétalos',
  'Nectar':'Néctar',
  'Pollen':'Polen',
  'Scavenged scraps':'Sobras carroñadas',
  'Insects and grubs':'Insectos y larvas',
  'Worms':'Gusanos',
  'Anything':'Cualquier cosa',
  '[[Faecium|Faeces]]':'Heces',
  'Birds':'Aves',
  'Scavenged remains':'Restos carroñados',
  'Partially-digested meat':'Carne parcialmente digerida',
  'Eggs':'Huevos',
  'Steals from others':'Roba a otros',
  '[[Venom Urchin]]s':'Erizos de mar venenosos',
  'Foraged leftovers':'Restos rebuscados',
  'Small animals':'Animales pequeños',
  'Old bones':'Huesos viejos',
  '[[Mordite]]':'Mordita',
  'Carnivorous':'Carnívoro',
  'Meat-eater':'Carnívoro',
  'Hypnotises prey':'Hipnotiza a sus presas',
  'Crunches bones':'Tritura huesos',
  'Blood-drinker':'Bebedor de sangre',
  'Liquidised organs':'Órganos licuados',
  'Extracts bone marrow':'Extrae la médula ósea',
  'Organs':'Órganos',
  'Raw meat':'Carne cruda',
  'Flesh-eater':'Carnívoro',
  'Hypercarnivore':'Hipercarnívoro',
  'Brain matter':'Materia gris',
  'Sinew':'Tendón',
  'Fresh meat':'Carne fresca',
  'Corpses':'Cadáveres',
  'Putrefied meat':'Carne putrefacta',
  'Cannibal':'Caníbal',
  'Offal':'Vísceras',
  'Removed hearts':'Corazones extraídos',
  'Other carnivores':'Otros carnívoros',
  'Large mammals':'Mamíferos grandes',
  'Flesh chunks':'Trozos de piel',
  'Meat chunks':'Trozos de carne',
  'Coagulated blood':'Sangre coagulada',
  'Frozen meat':'Carne congelada',
  'Boiled meat':'Carne cocida',
  'Radioactive meat':'Carne radiactiva',
  'Toxic meat':'Carne tóxica',
  'Rotten meat':'Carne podrida',
  'Preserved meat':'Carne preservada',
  'Fetid meat':'Carne fétida',
  'Charred meat':'Carne carbonizada',
  'Marine snow':'Nieve marina',
  'Chemosynthesis':'Quimiosíntesis',
  'Vented minerals':'Minerales agujereados',
  'Plankton':'Plancton',
  'Seaweed':'Algas marinas',
  'Deepwater algae':'Algas de aguas profundas',
  'Small crustaceans':'Pequeños crustáceos',
  'Rotten wood':'Madera podrida',
  'Decayed plant life':'Vegetación descompuesta',
  'Marine detritus':'Detritus marinos',
  'Algal particulates':'Partículas de algas',
  'Coral':'Coral',
  'Living sponges':'Esponjas vivas',
  'Deepwater spores':'Esporas de aguas profundas',
  'Nibbles at moss':'Mordisquea musgo',
  'Hydrothermal minerals':'Minerales hidrotermales',
  'Water filtration':'Filtración de agua',
  'Drifting plants':'Plantas a la deriva',
  'Silicates':'Silicatos',
  'High in calcium':'Alto contenido en calcio',
  'Water vines':'Vides de agua',
  '[[Kelp Sac|Kelp sacs]]':'Sacos de algas marinas',
  'Nutritious water weeds':'Hierbas de agua nutritivas',
  'Other fish':'Otros peces',
  'Cannibalism':'Canibalismo',
  'Marine eggs':'Huevos marinos',
  'Turtles':'Tortugas',
  'Shellfish':'Moluscos',
  'Drifting carcasses':'Cadáveres a la deriva',
  'Bones':'Huesos',
  'Hunts squid':'Caza calamares',
  'Brined organs':'Órganos salados',
  'Salinated flesh':'Carne salinizada',
  'Brains':'Cerebro',
  'Blood':'Sangre',
  'Gelatinous chunks':'Trozos gelatinosos',
  'Wasteflesh':'Carne de desecho',
  'Pure Silicon':'Silicio puro',
  'Siphoned Data':'Datos absorbidos',
  '[[Nanite Cluster]]s':'Cúmulos de nanites',
  'Recycled Heat':'Calor reciclado',
  'Cosmic Rays':'Rayos cósmicos',
  'Decaying Atoms':'Átomos deteriorados',
  'Random':'Aleatoria',
  'Interlopers':'Intrusos',
}
export default creatureDietDatalist;