/**
 * @fileoverview Provides data for creature datalists
 */
const creatureNotesDatalist:
{ [key: string]: string
} = {
		'Organic Interior':'Interior orgánico',
		'Magnetic Shell':'Caparazón magnético',
		'Self-Greasing':'Autolubricante',
		'Searching for home':'Buscando su hogar',
		'Wonders why':'Se hace preguntas',
		'Waiting for infinity':'Esperando al infinito',
		'Transmitting to the Atlas':'Transmitiendo al Atlas',
		'Remembers the Before':'Recuerda el ayer',
		'Non-simulated':'No simulado',
		'Solar Powered':'Consume energía solar',
		'[ Internal battery leak detected ]':'[Fuga detectada en la batería interna]',
		'Unscannable':'No se le puede escanear',
		'Recycled':'Reciclado',
		'Self-constructed':'Autoconstruido',
		'Assembled in the stars':'Ensamblado en las estrellas',
		'Superconducting wires':'Cables superconductores',
		'Enlarged flux circuit':'Circuito de flujo alargado',
		'Distributed cores':'Núcleos distribuidos',
		'Divergent':'Divergente',
		'Self-aware':'Consciente de sí mismo',
		'Chooses not to speak':'Decide no hablar',
		'Underclocked':'Rendimiento reducido',
		'Overclocked':'Rendimiento aumentado',
		'Air-cooled':'Refrigerado por aire',
		'Graphene wiring':'Cableado de grafeno',
		'Many hidden toes':'Muchos dedos ocultos',
		'Builds metal nest':'Construye nidos metálicos',
		'Dislikes bright colours':'No le gustan los colores brillantes',
		'Moon Baby':'Nocturna',
		'Lays beautiful eggs':'Pone huevos preciosos',
		'Waxy all-over':'Tinen cera por todas partes',
		'Secretes venom':'Segrega veneno',
		'Compound eyes':'Ojos compuestos',
		'Inverted organ sacs':'Cavidad de órganos invertida',
		'Good pollinator':'Buena polinizadora',
		'Ultrasonic roar':'Rugido ultrasónico',
		'Retractable appendages':'Apéndices retráctiles',
		'Has no bones':'No tiene huesos',
		'Not carbon based':'No se basa en carbono',
		'Evil':'Malvada',
		'Nutritious faeces':'Heces nutritivas',
		'Asexual reproduction':'Reproducción asexual',
		'Changes gender when cold':'Cambia de género cuando hace frío',
		'Can dislocate jawbones':'Puede dislocar maxilares',
		'Powerful mandibles':'Mandíbulas potentes',
		'Autonomous regeneration':'Regeneración autónoma',
		'Technically immortal':'Técnicamente inmortal',
		'Blue blood':'Sangre azul',
		'Green blood':'Sangre verde',
		'Yellow blood':'Sangre amarilla',
		'Excess of bile':'Exceso de bilis',
		'Creates beautiful webs':'Crea hermosas telarañas',
		'Strong burrower':'Gran excavadora',
		'Hibernates':'Hiberna',
		'Mates for life':'Se aparea de por vida',
		'Carries symbiotic fungus':'Porta hongos simbióticos',
		'Stomach inside skull':'Tiene el estómago dentro del cráneo',
		'Nine additional senses':'Nueve sentidos adicionales',
		'Sense organs in feet':'Órganos de los sentidos en los pies',
		'Excellent sense of smell':'Excelente sentido del olfato',
		'Poor hearing':'Mal oído',
		'Ticklish':'Picajosa',
		'Highly intelligent':'Muy inteligente',
		'Cannot see colour':'No puede ver colores',
		'Sprays ink when scared':'Expulsa tinta cuando se asusta',
		'Produces vile stench':'Produce un hedor nauseabundo',
		'Unpleasant to eat':'Desagradable para el consumo',
		'Gelatinous bones':'Huesos gelatinosos',
		'Can change colour':'Puede cambiar de color',
		'Chromatophore':'Cromatóforos',
		'Rapid self-healing':'Autocuración rápida',
		'Valuable blood':'Sangre valiosa',
		'Absorbs moisture from air':'Absorbe humedad del aire',
		'Mildly radioactive':'Ligeramente radiactiva',
		'Strongly radioactive':'Altamente radiactiva',
		'Hybrid species':'Especie híbrida',
		'Genetically unstable':'Genéticamente inestable',
		'Partially domesticated':'Parcialmente domesticada',
		'Gentle soul':'Amable',
		'Hidden extra skull':'Cráneo adicional oculto',
		'Secondary skin':'Piel secundaria',
		'Hidden extra tongue':'Lengua adicional oculta',
		'Redundant internal organs':'Órganos internos redundantes',
		'Rigid bones':'Huesos rígidos',
		'Hidden extra claws':'Garras adicionales ocultas',
		'Six stomachs':'Seis estómagos',
		'Powerful digestive enzymes':'Potentes enzimas digestivas',
		'Saliva pH 14':'Saliva de pH 14',
		'Flexible joints':'Articulaciones flexibles',
		'Hidden stinger':'Aguijón oculto',
		'Covered in tiny hairs':'Cubierta de diminutos pelos',
		'Untameable':'Indomesticable',
		'Fragile skull':'Cráneo frágil',
		'Fragile skin':'Piel frágil',
		'Detachable tongue':'Lengua extraíble',
		'Bruisable organs':'Órganos expuestos',
		'Brittle bones':'Huesos quebradizos',
		'Calcified claws':'Garras calcificadas',
		'Translucent teeth':'Dientes translúcidos',
		'Caustic skin':'Piel cáustica',
		'Toxic tongue':'Lengua tóxica',
		'Covered in toxic bristles':'Cubierta de cerdas tóxicas',
		'Venom-laden claws':'Garras cargadas de veneno',
		'Armoured skull':'Cráneo blindado',
		'Regularly sheds skin':'Muda la piel con regularidad',
		'Monstrous tongue':'Lengua monstruosa',
		'Tiny organs':'Órganos diminutos',
		'Metal bones':'Huesos metálicos',
		'Bioluminescent teeth':'Dientes bioluminiscentes',
		'Thick skull':'Cráneo grueso',
		'Toughened skin':'Piel endurecida',
		'Massive tongue':'Lengua enorme',
		'Stores water in hidden sacs':'Almacena agua en receptáculos ocultos',
		'Sheds and regrows bones':'Muda y regenera los huesos',
		'Sharp claws':'Garras afiladas',
		'Rubber skull':'Cráneo de caucho',
		'Porous skin':'Piel porosa',
		'Regrows teeth each day':'Regenera los dientes cada día',
		'Grows lungs after birth':'Desarrolla pulmones después de nacer',
		'Carbon-based skeleton':'Esqueleto basado en carbono',
		'Decentralised nervous system':'Sistema nervioso descentralizado',
		'Skull full of holes':'Cráneo lleno de agujeros',
		'Skin parasites':'Parásitos en la piel',
		'Tongue parasites':'Parásitos en la lengua',
		'Extensive gut bacteria':'Gran bacteria intestinal',
		'Digests via symbionts':'Digiere a través de simbiontes',
		'Claws harbour disease':'Garras que albergan enfermedades',
		'Spawns in water':'Desova en el agua',
		'Goes underground to die':'Va bajo tierra a morir',
		'Tapeworm host':'Portadora de solitaria',
		'Delicious':'Deliciosa',
		'Easily trained':'Fácil de adiestrar',
		'Inflates when stressed':'Se hincha cuando se estresa',
		'Poor sense of direction':'Mal sentido de la orientación',
		'Excellent navigator':'Navegadora excelente',
		'Can sense magnetic fields':'Puede percibir los campos magnéticos',
		'Easily confused':'Se confunde con facilidad',
		'Frequently lost':'Se pierde con frecuencia',
		'Hears ground vibrations':'Escucha las vibraciones terrestres',
		'Scared of fire':'Tiene miedo al fuego',
		'Hydrophobic':'Hidrofóbica',
		'Vestigial udders':'Ubres vestigiales',
		'Makes art with sticks':'Realiza obras artísticas con palos',
		'Recognises other species':'Reconoce a otras especies',
		'Beloved by the [[Gek]]':'Adorada por los [[Gek]]',
		'Bonds with [[Vy\'keen]]':'La unen lazos con los [[Vy\'keen]]',
		'Hunts [[Sentinel]]s':'Caza [[Centinelas]]',
		'Matriarchal society':'Sociedad matriarcal',
		'Digs underground nests':'Excava nidos subterráneos',
		'One extendible finger':'Tiene un dedo extensible',
		'Grows wings before death':'Le crecen alas antes de morir',
		'Alluring pheromones':'Feromonas atrayentes',
		'Sings beautifully':'Canta de maravilla',
		'Deceptively fast':'Engañosamente rápida',
		'Lacks gallbladder':'Carece de vesícula biliar',
		'Both gills and lungs':'Tiene branquias y pulmones',
		'Respires inorganically':'Respira de forma inorgánica',
		'Has chlorophyll glands':'Tiene glándulas de clorofila',
		'Sleeps standing up':'Duerme de pie',
		'Never blinks':'Nunca parpadea',
		'Frequently regurgitates':'Regurgita con frecuencia',
		'Irritable':'Irritable',
		'Highly social':'Muy sociable',
		'Dislikes being scanned':'No le gusta que la escaneen',
		'Telepathic':'Telepática',
		'Burns in the sun':'Se quema al sol',
		'Well insulated':'Bien aislada',
		'Photosensitive':'Fotosensible',
		'Secretes phytotoxins':'Segrega fitotoxinas',
		'Lovely eyes':'Ojos preciosos',
		'Good parent':'Buena progenitora',
		'Can feel love':'Puede sentir amor',
		'Screams when upset':'Grita cuando la molestan',
		'Forms colonies':'Forma colonias',
		'Hatched from cocoons':'Nace de capullos',
		'Fragrant':'Aromática',
		'Particularly oily':'Bastante grasienta',
		'Gets cold easily':'Se enfría con facilidad',
		'Drinks blood':'Bebe sangre',
		'Does not age':'No envejece',
		'Always waiting':'Siempre está a la espera',
		'Always watching':'Siempre está vigilante',
		'Aware of its fate':'Es consciente de su destino',
		'Senses ATLAS':'Percibe el ATLAS',
		'Limited sentience':'Conciencia limitada',
		'Born on meteors':'Nace en meteoritos',
		'Laden with nectar':'Cargada de néctar',
		'Occasionally eats rocks':'En ocasiones, consume rocas',
		'Scared of mirrors':'Tiene miedo a los espejos',
		'Eyes regrow after damage':'Regenera los ojos cuando sufren daños',
		'Superheated stomach':'Estómago sobrecalentado',
		'Three hearts':'Tres corazones',
		'Two livers':'Dos hígados',
		'Acidic blood':'Sangre ácida',
		'Respires anaerobically':'Respira de forma anaeróbica',
		'Carries symbiotic worms':'Porta gusanos simbióticos',
		'Riddled with pests':'Llena de parásitos',
		'Carries babies in pouch':'Porta a sus bebés en una bolsa',
		'Promiscuous':'Promiscua',
		'Symmetrical insides':'Entrañas simétricas',
		'Occasionally invisible':'Se hace invisible en ocasiones',
		'Limited mind control':'Control mental limitado',
		'Buries food supplies':'Entierra reservas de comida',
		'Cannot sweat':'No puede sudar',
		'Weak lungs':'Pulmones débiles',
		'Strong swimmer':'Gran nadadora',
		'Made of stardust':'Hecha de polvo estelar',
		'Requires dietary iron':'Necesita hierro dietético',
		'Magnetic teeth':'Dientes magnéticos',
		'Retractable eyestalks':'Globos oculares retráctiles',
		'Breathes through mouth':'Respira a través de la boca',
		'Smells with tongue':'Huele con la lengua',
		'Cannot drown':'No se puede sumergir',
		'Highly fertile':'Muy fértil',
		'Nitrogen-rich blood':'Sangre rica en nitrógeno',
		'Bioluminescent blood':'Sangre bioluminiscente',
		'Fears the rain':'Tiene miedo a la lluvia',
		'Echolocation glands':'Glándulas de ecolocalización',
		'Possesses language':'Posee lenguaje',
		'Varied phenotype':'Fenotipo variado',
		'Tiny brain':'Cerebro diminuto',
		'Cannot digest starch':'No puede digerir el almidón',
		'Seeks red flowers':'Busca flores rojas',
		'Nests in blue foliage':'Anida en follajes azules',
		'Elaborate mating displays':'Realiza rituales de apareamiento',
		'Brain hemispheres not linked':'Hemisferios cerebrales no unidos',
		'Sweats milk for infants':'Suda leche para sus crías',
		'No stomach':'Sin estómago',
		'Double-coned eyes':'Ojos de doble cono',
		'Cutaneous respiration':'Respiración cutánea',
		'Barbed feet':'Pies con púas',
		'Extremely homozygous':'Extremadamente homocigótico',
		'Extremely heterozygous':'Extremadamente heterocigótico',
		'Parasites in brain':'Parásitos en el cerebro',
		'Night vision':'Visión nocturna',
		'But there is something particularly unsettling about this creature, some deep shadow hanging over them. They are to be treated with extreme caution.':'Pero hay algo especialmente perturbador en esta criatura, ...',
		'Skeletal analysis reveals unusually supple bones, as if they had only recently grown: possible defense mechanism to shed and rapidly regrow body parts?':'Análisis óseos han revelado que tiene huesos inusualmente flexibles, como ...',
    '00007FF69A5CF443  cmp  qword ptr [rsi+2E8h],r13':'00007FF69A5CF443  cmp  qpalabra ptr [rsi+2E8h],r13',
    '00007FF69A5CF456  cmp  byte ptr [gbIgnore (07FF69E4BE31Fh)],0':'00007FF69A5CF456 cmp byte ptr [gbIgnorar (07FF69E4BE31Fh)],0',
    '00007FF69A5CF46A  lea  rcx,[string  (07FF69B63A7F4h)]':'00007FF69A5CF46A lea rcx,[cadena (07FF69B63A7F4h)]',
    '00007FF69A5CF497  mov  qword ptr [rsp+40h],rax':'00007FF69A5CF497  mov  qpalabra ptr [rsp+40h],rax',
    '00007FF69A5CF482  movdqu  xmmword ptr [rsp+60h],xmm0':'00007FF69A5CF482  movdqu  xmmpalabra ptr [rsp+60h],xmm0',
    '00007FF69A5CF48F  mov  dword ptr [rsp+48h],92Fh':'00007FF69A5CF48F  mov  dpalabra ptr [rsp+48h],92Fh',
    '00007FF69A5CF4A1  movups  xmm0,xmmword ptr [rsp+38h]':'00007FF69A5CF4A1  movups  xmm0,xmmpalabra ptr [rsp+38h]',
    '00007FF69A5CF4B2  mov  qword ptr [rsp+50h],rax':'00007FF69A5CF4B2  mov  qpalabra ptr [rsp+50h],rax',
    '00007FF69A5CF4B7  lea rdx,[gbIgnore (07FF69E4BE31Fh)]':'00007FF69A5CF4B7  lea rdx,[gbIgnorar (07FF69E4BE31Fh)]',
    '00007FF69A5CF4D6  movups xmm1,xmmword ptr [rsp+68h]':'00007FF69A5CF4D6  movups xmm1,xmmpalabra ptr [rsp+68h]',
    '00007FF712E2305D  movzx  edx,dx':'00007FF712E2305D  movzx  edx,dx',
    '00007FF712E23060  shl  edx,10h':'00007FF712E23060  shl  edx,10h',
    '00007FF712E23063  movzx  cx,r8w':'00007FF712E23063  movzx  cx,r8w',
    '00007FF712E23067  or  edx,ecx':'00007FF712E23067  o  edx,ecx',
    '00007FF712E23069  mov eax,r8d':'00007FF712E23069  mov eax,r8d',
    '00007FF712E2306C  lock   cmpxchg dword ptr [rdi],edx':'00007FF712E2306C  cierre   cmpxchg dpalabra ptr [rdi],edx',
    '00007FF712E22F04  mov  rax,qword ptr [rsi+8]':'00007FF712E22F04  mov  rax,qpalabra ptr [rsi+8]',
    '00007FF712E22F08  mov  rcx,qword ptr [r9+rax+10h]':'00007FF712E22F08  mov  rcx,qpalabra ptr [r9+rax+10h]',
    '00007FF712E22F0D  mov  eax,dword ptr [rcx]':'00007FF712E22F0D  mov  eax,dpalabra ptr [rcx]',
    '00007FF712E22F0F  mov  rcx,qword ptr [rsi+10h]':'00007FF712E22F0F  mov  rcx,qpalabra ptr [rsi+10h]',
    '00007FF712E22F13  test  eax,eax':'00007FF712E22F13  prueba eax,eax',
}

export default creatureNotesDatalist;
