/**
 * @fileoverview Provides data for flora datalists
 */
const floraDatalists = {
	floraNotesData: [
		'Mono-Seasonal',
		'Sensitive to Light',
		'Potentially Medicinal',
		'Hollow',
		'Insect Habitation',
		'Toxic Bark',
		'Bitter Stems',
		'Unpollinated',
		'Bioluminescent',
		'Succulent Tubers',
		'Waxy Fruit',
		'Infrequent Flowering',
		'Edible Seeds',
		'Inconsistent Blossom',
		'Inedible Petals',
		'Pungent',
		'Nocturnal Pollinators',
		'Parasite Host',
		'Omni-Seasonal',
		'Bi-Seasonal',
		'Caustic Sap',
		'Psychotropic Leaves',
		'Hallucogenic Bark',
		'Extendible Fronds',
		'Stinging Hairs',
		'Annual Spore Clouds',
		'Sentient Fruit',
		'Hidden Tentacles',
		'Itchy Pollen',
		'Hypnotic Perfume',
		'Calming Scent',
		'Pheromone Sacs',
		'Translucent Nuts',
		'Crepuscular Fruit',
		'Self-Healing Bark',
		'Delicate Stems',
		'Irresistible Seeds',
		'Wailing Roots',
		'Umbral Sprouts',
		'Movement Prone',
		'Airborne Seeds',
		'Multicolour Wood',
		'Photosensitive Tendrils',
		'Iridescent Seed Pods',
		'Retractable Fronds',
		'Metallic Nodules',
		'Partially Developed Eyes',
		'Sneaky',
		'Whispering Leaves',
		'Haunted Nests',
		'Nesting Moths',
		'Unripe Fruit',
		'Inner Beauty',
		'Hibernating',
		'Biologically Inert',
		'Self-Pollinating',
		'Inaudible',
		'Frost Resistant',
		'Carbon Dense',
		'Delicious',
		'Proto-Skeletal',
		'Ticklish Stamen',
		'Four Dimensional',
		'Ocular Irritant',
		'Mist-Based Defences',
		'Cloud Generator',
		'Pharmacologically Active',
		'Altitude Tolerant',
		'Drought Resistant',
		'Tidal Sap',
		'Easily Startled',
		'Meaty Roots',
		'True Neutral',
		'All Colours',
		'Blight Resistant',
		'Water Laden',
		'Durable Fruit',
		'Wind-Blown Seeds',
		'Mobile',
		'Genetically Diverse',
		'Cloned',
		'Rapidly Mutating',
		'Faintly Singing',
		'Pleasing Aroma',
		'Slowly Rotting',
		'Extremely Poisonous',
		'High Metal Content',
		'Liquidises Soil',
		'High Internal Pressure',
		'Unstable Fruit',
		'Covered in Tiny Eggs',
		'Aggressive',
		'Golden Sap',
		'Flakey Coating',
		'Suspicious Odour',
		'Vigorous',
		'Hydrophilic',
		'Ericaceous',
		'Calcifuge',
		'Calcicole',
		'Odourless',
		'Spongy Coating',
		'Parasitic Leaves',
		'Tiny Hairs',
		'Sticky Coating',
		'Nanite Sap',
		'Water Resistant',
		'Choking Scent',
		'Flowers Once',
		'Infectious Spores',
		'Hive Mind',
		'Extraterrestrial',
		'Migratory',
		'Perennial',
		'Self-Propagating',
		'Rapid Reproduction',
		'Self-Replicating',
		'Slow Growing',
		'Fragile Stems',
		'Delicate Flowers',
		'Paralysing Spores',
		'Neurotoxic Pollen',
		'Oily Seeds',
		'Stinging Fruit',
		'Crimson Seeds',
		'Fireproof Nuts',
		'Crystalline Flowers',
		'Shadow Petals',
		'Combustible Fruit',
		'Glasslike Seeds',
		'Fragile Bulbs',
		'Mouldy Bulbs',
		'Semi-Liquid Bulbs',
		'Luminous Bulbs',
		'Glowing Tubers',
		'Spreading Tubers',
		'Toxic Thorns',
		'Launchable Thorns',
		'Invisible Bristles',
		'Internal Branches',
		'Inaudible Singing',
		'Haunted Roots',
		'Internal Teeth',
		'Fungal Soul',
		'Must Not Be Touched',
		'Favoured by Atlas',
		'Enraged at Fate',
		'Doomed',
		'Lost in Time',
		'Already Dying',
		'Hungry for Stars',
		'Thirsting for Glass',
		'Howls When Alone',
		'Unbound Seeds',
		'Rooted in the Beyond',
		'Yearning',
		'Blood Sap',
		'Crimson Spores',
		'Infinite Branches',
		'Complex Nervous System',
		'Partially Skeletal',
		'Sees in the Dark',
		'Lonely',
		'Searching for a Host',
		'Nightstalker',
		'Sap Binds Permanently',
		'Roots can Talk',
		'Decentralised Mind',
		'Senses Beyond the Soil',
		'Longs to be Consumed',
		'Can Sense You',
		'Lacks Spirit',
		'Invasive',
		'Searches For The Light',
		'Diseased',
		'[BREACH POINT]',
		'[BOUNDARY FAILURE]',
		'[ANOMALOUS]',
		'[ITERATION ERROR]',
		'[CORRUPTED ENTITY]',
	],
	ageData: [
		'Ancient',
		'Old',
		'Timeless',
		'Millenia',
		'Centuries',
		'Fresh',
		'Sproutling',
		'Sapling',
		'Young',
		'Decades',
		'Moderate',
		'Mature',
		'Seasoned',
		'Juvenile',
		'Fully Grown',
		'Youthful',
		'Advanced',
		'Unknown',
		'Indeterminate',
		'Regenerating',
		'Perpetual',
		'Cyclical',
		'Several Days',
		'Still Growing',
		'Infant',
		'Immature',
		'Fully Developed',
		'Dying',
	],
	nutSourceData: [
		'Plankton',
		'Ensnares Fish',
		'Coral Microcolony',
		'Oxygen Filtration',
		'Mineral Filtration',
		'Hydrosynthesis',
		'Salt Absorption',
		'Vented minerals',
		'Plankton Symbiotes',
		'Algal particulates',
		'Nutrient Source',
		'Decomposition',
		'Fungal Harvest',
		'Air Leaching',
		'Photosynthesis',
		'Carnivorous',
		'Radiotrophic',
		'Free Radicals',
		'Autotrophic',
		'Parasitic Leaching',
		'Infrared Radiation',
		'Entrapment',
		'Conjuration',
		'Atmospheric Moisture',
		'Osmosis',
		'Lost Insects',
		'Gas Clouds',
		'Heavy Rain',
		'Electron Donors',
		'Fungal Symbiosis',
		'Membrane Compression',
		'Nitrogen Fixation',
		'Carbon Absorption',
		'Soil Recycling',
		'Radio Waves',
		'Meditation',
		'Fungal Reclamation',
		'Proton Recycling',
		'Salt Fusion',
		'Soil Bacteria',
		'Natural Carbon',
		'Buried Treasure',
		'Buried Carbon',
		'Buried Nitrogen',
		'Underground Bubbles',
		'Moonlight',
		'Sunlight',
		'Ultraviolet Radiation',
		'Gamma Rays',
		'Sublimated Nitrogen',
		'Rock Enzymes',
		'Carnivorous Roots',
		'Fermented Corpses',
		'Aerobic Digestion',
		'Anaerobic Digestion',
		'Theft',
		'Cosmic Radiation',
		'Heat Recycling',
		'Geological Energy',
		'Thermal Capture',
		'Liquid Ammonia',
		'Other Plants',
		'External Maintenance',
		'Gravitational Waves',
		'Stray Particles',
		'Time Threads',
		'Lost Travellers',
		'[UNKNOWN]',
		'[NOT DETERMINED]',
		'Predatory',
		'Self-Sustaining',
		'The Unfortunate',
		'The Lost',
		'Doomed Wanderers',
		'Non-existent Insects',
		'Anomalous Nutrients',
		'Heavy Metals',
		'Stardust',
		'Feeds on Failure',
		'Dark Matter',
		'Dark Energy',
		'Time Bubbles',
		'Synthesised from Fire',
	],
	rootData: [
		'Complex',
		'Fractal',
		'Widespread',
		'Stunted',
		'Swamped',
		'Desiccated',
		'Extensive',
		'Concentrated',
		'Symbiotic',
		'Fungal',
		'Localised',
		'Bi-directional',
		'Many-Limbed',
		'Gravitational',
		'Unsupported',
		'Inorganic',
		'Significant',
		'Efficient',
		'Far Reaching',
		'Capacious',
		'Limited',
		'Narrow',
		'Restricted',
		'Parasitic',
		'Invasive',
		'Extendable',
		'Voluminous',
		'Global',
		'Knotted',
		'Linear',
		'Branching',
		'Substantial',
		'Conventional',
		'Circular',
		'Independent',
		'Sentient',
		'Heat Seeking',
		'Simple',
		'Regular',
		'Polygonal',
		'Not Present',
		'Hidden',
		'Balanced',
		'Omni-Directional',
		'Irregular',
		'Transferrable',
		'Mobile',
		'Obtuse',
		'Unfathomable',
		'Grasping',
	],
	floraResources: [
		'',
		'Oxygen',
		'Carbon',
		'Sodium',
		'Condensed Carbon',
		'Cyto-Phosphate',
		'Marrow Bulb',
		'Kelp Sac',
		'Salt',
	]
}

export default floraDatalists;