/**
 * @fileoverview Provides data for flora datalists
 */
const floraNotesDatalist:
{ [key: string]: string
} = {
		'Mono-Seasonal':'Monotemporal',
		'Sensitive to Light':'Sensible a la luz',
		'Potentially Medicinal':'Potencialmente medicinal',
		'Hollow':'Hueca',
		'Insect Habitation':'Morada de insectos',
		'Toxic Bark':'Corteza tóxica',
		'Bitter Stems':'Tallos amargos',
		'Unpollinated':'No polinizada',
		'Bioluminescent':'Bioluminiscente',
		'Succulent Tubers':'Tubérculos carnosos',
		'Waxy Fruit':'Fruto ceroso',
		'Infrequent Flowering':'Floración poco frecuente',
		'Edible Seeds':'Semillas comestibles',
		'Inconsistent Blossom':'Flores irregulares',
		'Inedible Petals':'Pétalos no comestibles',
		'Pungent':'Acre',
		'Nocturnal Pollinators':'Polinizadores nocturnos',
		'Parasite Host':'Huésped de parásitos',
		'Omni-Seasonal':'Omnitemporal',
		'Bi-Seasonal':'Bitemporal',
		'Caustic Sap':'Savia cáustica',
		'Psychotropic Leaves':'Hojas psicotrópicas',
		'Hallucogenic Bark':'Corteza alucinógena',
		'Extendible Fronds':'Frondas extensibles',
		'Stinging Hairs':'Pelos urticantes',
		'Annual Spore Clouds':'Nubes de esporas anuales',
		'Sentient Fruit':'Fruto sensible',
		'Hidden Tentacles':'Tentáculos ocultos',
		'Itchy Pollen':'Polen urticante',
		'Hypnotic Perfume':'Perfume hipnótico',
		'Calming Scent':'Aroma tranquilizador',
		'Pheromone Sacs':'Bolsas de feromonas',
		'Translucent Nuts':'Nueces translúcidas',
		'Crepuscular Fruit':'Fruto crepuscular',
		'Self-Healing Bark':'Corteza autorregenerativa',
		'Delicate Stems':'Tallos delicados',
		'Irresistible Seeds':'Semillas irresistibles',
		'Wailing Roots':'Raíces quejumbrosas',
		'Umbral Sprouts':'Brotes en umbral',
		'Movement Prone':'Propensa al movimiento',
		'Airborne Seeds':'Semillas aéreas',
		'Multicolour Wood':'Madera multicolor',
		'Photosensitive Tendrils':'Zarcillos fotosensibles',
		'Iridescent Seed Pods':'Vainas de semillas iridiscentes',
		'Retractable Fronds':'Frondas retráctiles',
		'Metallic Nodules':'Nódulos metálicos',
		'Partially Developed Eyes':'Ojos parcialmente desarrollados',
		'Sneaky':'Furtiva',
		'Whispering Leaves':'Hojas susurrantes',
		'Haunted Nests':'Nidos angustiosos',
		'Nesting Moths':'Nidos de polillas',
		'Unripe Fruit':'Fruto verde',
		'Inner Beauty':'Belleza interior',
		'Hibernating':'Hibernadora',
		'Biologically Inert':'Biológicamente inerte',
		'Self-Pollinating':'Autopolinizadora',
		'Inaudible':'Inaudible',
		'Frost Resistant':'Resistente al frío',
		'Carbon Dense':'Densidad de carbono',
		'Delicious':'Deliciosa',
		'Proto-Skeletal':'Protoesqueleto',
		'Ticklish Stamen':'Estambre irritante',
		'Four Dimensional':'Cuatridimensional',
		'Ocular Irritant':'Irritante ocular',
		'Mist-Based Defences':'Defensas lacrimales',
		'Cloud Generator':'Productora de nubes',
		'Pharmacologically Active':'Farmacológicamente activa',
		'Altitude Tolerant':'Resistente a la altitud',
		'Drought Resistant':'Resistente a la sequía',
		'Tidal Sap':'Savia mareal',
		'Easily Startled':'Asustadiza',
		'Meaty Roots':'Raíces carnosas',
		'True Neutral':'Totalmente neutral',
		'All Colours':'Todos los colores',
		'Blight Resistant':'Resistente a la roya',
		'Water Laden':'Cargada de agua',
		'Durable Fruit':'Fruto duradero',
		'Wind-Blown Seeds':'Semillas al viento',
		'Mobile':'Móvil',
		'Genetically Diverse':'Genéticamente diversa',
		'Cloned':'Clonada',
		'Rapidly Mutating':'De mutación rápida',
		'Faintly Singing':'De canturreo débil',
		'Pleasing Aroma':'Aroma embriagador',
		'Slowly Rotting':'De putrefacción lenta',
		'Extremely Poisonous':'Extremadamente venenosa',
		'High Metal Content':'Alto contenido en metal',
		'Liquidises Soil':'Licua el suelo',
		'High Internal Pressure':'Alta presión interna',
		'Unstable Fruit':'Fruto inestable',
		'Covered in Tiny Eggs':'Cubierta de huevos diminutos',
		'Aggressive':'Agresiva',
		'Golden Sap':'Savia dorada',
		'Flakey Coating':'Cubierta escamosa',
		'Suspicious Odour':'Olor sospechoso',
		'Vigorous':'Vigorosa',
		'Hydrophilic':'Hidrófila',
		'Ericaceous':'Ericácea',
		'Calcifuge':'Calcífuga',
		'Calcicole':'Calcícola',
		'Odourless':'Inodora',
		'Spongy Coating':'Capa esponjosa',
		'Parasitic Leaves':'Hojas parasitarias',
		'Tiny Hairs':'Pelos diminutos',
		'Sticky Coating':'Cubierta pegajosa',
		'Nanite Sap':'Savia de nanites',
		'Water Resistant':'Resistente al agua',
		'Choking Scent':'Aroma asfixiante',
		'Flowers Once':'Florece una vez',
		'Infectious Spores':'Esporas infecciosas',
		'Hive Mind':'Mente de colmena',
		'Extraterrestrial':'Extraterrestre',
		'Migratory':'Migratoria',
		'Perennial':'Perenne',
		'Self-Propagating':'Autopropagadora',
		'Rapid Reproduction':'Reproducción rápida',
		'Self-Replicating':'Autorreplicante',
		'Slow Growing':'De crecimiento lento',
		'Fragile Stems':'Tallos frágiles',
		'Delicate Flowers':'Flores delicadas',
		'Paralysing Spores':'Esporas paralizantes',
		'Neurotoxic Pollen':'Polen neurotóxico',
		'Oily Seeds':'Semillas aceitosas',
		'Stinging Fruit':'Fruto urticante',
		'Crimson Seeds':'Semillas carmesí',
		'Fireproof Nuts':'Nueces ignífugas',
		'Crystalline Flowers':'Flores cristalinas',
		'Shadow Petals':'Pétalos sombríos',
		'Combustible Fruit':'Fruto combustible',
		'Glasslike Seeds':'Semillas vidriosas',
		'Fragile Bulbs':'Bulbos frágiles',
		'Mouldy Bulbs':'Bulbos mohosos',
		'Semi-Liquid Bulbs':'Bulbos semilíquidos',
		'Luminous Bulbs':'Bulbos luminosos',
		'Glowing Tubers':'Tubérculos brillantes',
		'Spreading Tubers':'Bulbos extensibles',
		'Toxic Thorns':'Espinas tóxicas',
		'Launchable Thorns':'Espinas lanzables',
		'Invisible Bristles':'Púas invisibles',
		'Internal Branches':'Ramas internas',
		'Inaudible Singing':'Canturreo inaudible',
		'Haunted Roots':'Raíces encantadas',
		'Internal Teeth':'Dentadura interna',
		'Fungal Soul':'Alma fúngica',
		'Must Not Be Touched':'No tocar',
		'Favoured by Atlas':'Preferido del Atlas',
		'Enraged at Fate':'Enfurecido por el destino',
		'Doomed':'Condenado',
		'Lost in Time':'Perdido en el tiempo',
		'Already Dying':'Agonizando',
		'Hungry for Stars':'Hambriento de estrellas',
		'Thirsting for Glass':'Sediento de cristal',
		'Howls When Alone':'Aullando en solitario',
		'Unbound Seeds':'Semillas sueltas',
		'Rooted in the Beyond':'Enraizado en el más allá',
		'Yearning':'Anhelante',
		'Blood Sap':'Savia sangrienta',
		'Crimson Spores':'Esporas carmesí',
		'Infinite Branches':'Ramas infinitas',
		'Complex Nervous System':'Sistema nervioso complejo',
		'Partially Skeletal':'Parcialmente esquelético',
		'Sees in the Dark':'Visión en la oscuridad',
		'Lonely':'Solitario',
		'Searching for a Host':'Buscando un huésped',
		'Nightstalker':'Acechador nocturno',
		'Sap Binds Permanently':'Savia unida de forma permanente',
		'Roots can Talk':'Raíces habladoras',
		'Decentralised Mind':'Mente descentralizada',
		'Senses Beyond the Soil':'Sentidos más allá del suelo',
		'Longs to be Consumed':'Deseando ser consumido',
		'Can Sense You':'Puede sentirte',
		'Lacks Spirit':'Falta de espíritu',
		'Invasive':'Invasivo',
		'Searches For The Light':'Buscando la luz',
		'Diseased':'Enfermo',
		'[BREACH POINT]':'[PUNTO DE BRECHA]',
		'[BOUNDARY FAILURE]':'[FALLO FRONTERIZO]',
		'[ANOMALOUS]':'[ANÓMALO]',
		'[ITERATION ERROR]':'[ERROR DE ITERACIÓN]',
		'[CORRUPTED ENTITY]':'[ENTIDAD CORRUPTA]',
}
export default floraNotesDatalist;