/**
 * @fileoverview Provides data for flora datalists
 */
const floranutSourceDatalist:
{ [key: string]: string
} = {
	'':'',
	'[NOT DETERMINED]':'[INDETERMINADO]',
	'[UNKNOWN]':'[DESCONOCIDO]',
	'Aerobic Digestion':'Digestión aeróbica',
	'Air Leaching':'Lixiviación de aire',
	'Anaerobic Digestion':'Digestión anaeróbica',
	'Anomalous Nutrients':'Nutrientes anómalos',
	'Atmospheric Moisture':'Humedad atmosférica',
	'Autotrophic':'Autotrófica',
	'Buried Carbon':'Carbono enterrado',
	'Buried Nitrogen':'Nitrógeno enterrado',
	'Buried Treasure':'Tesoro enterrado',
	'Carbon Absorption':'Absorción de carbono',
	'Carnivorous Roots':'Raíces carnívoras',
	'Carnivorous':'Carnívoro',
	'Conjuration':'Invocación',
	'Cosmic Radiation':'Radiación cósmica',
	'Dark Energy':'Energía oscura',
	'Dark Matter':'Materia oscura',
	'Decomposition':'Putrefacción',
	'Doomed Wanderers':'Nómadas condenados',
	'Electron Donors':'Donantes de electrones',
	'Entrapment':'Trampa',
	'External Maintenance':'Mantenimiento externo',
	'Fermented Corpses':'Cadáveres fermentados',
	'Free Radicals':'Radicales libres',
	'Fungal Harvest':'Recolecta fúngica',
	'Fungal Reclamation':'Reciclaje fúngico',
	'Fungal Symbiosis':'Simbiosis micótica',
	'Gamma Rays':'Rayos gamma',
	'Gas Clouds':'Nubes de gas',
	'Geological Energy':'Energía geológica',
	'Gravitational Waves':'Ondas gravitacionales',
	'Heat Recycling':'Reciclaje calórico',
	'Heavy Metals':'Metales pesados',
	'Heavy Rain':'Lluvia torrencial',
	'Infrared Radiation':'Radiación infrarroja',
	'Liquid Ammonia':'Amoniaco líquido',
	'Lost Insects':'Insectos perdidos',
	'Lost Travellers':'Viajeros perdidos',
	'Meditation':'Meditación',
	'Membrane Compression':'Comprensión de membrana',
	'Moonlight':'Luz lunar',
	'Natural Carbon':'Carbono natural',
	'Nitrogen Fixation':'Fijación de nitrógeno',
	'Non-existent Insects':'Insectos inexistentes',
	'Nutrient Source': 'Fuente de nutrientes',
	'Osmosis':'Ósmosis',
	'Other Plants':'Otras plantas',
	'Parasitic Leaching':'Lixiviación parasitaria',
	'Photosynthesis':'Fotosíntesis',
	'Predatory':'Depredador',
	'Proton Recycling':'Reciclaje de protones',
	'Radio Waves':'Ondas de radio',
	'Radiotrophic':'Radiotrófica',
	'Rock Enzymes':'Enzimas de roca',
	'Salt Fusion':'Fusión salina',
	'Self-Sustaining':'Autosostenible',
	'Soil Bacteria':'Bacterias del suelo',
	'Soil Recycling':'Reciclaje del suelo',
	'Stardust':'Polvo de estrellas',
	'Stray Particles':'Partículas extraviadas',
	'Sublimated Nitrogen':'Nitrógeno sublimado',
	'Sunlight':'Luz solar',
	'Synthesised from Fire':'Sintetizado a partir de fuego',
	'The Lost':'Los perdidos',
	'The Unfortunate':'Los desafortunados',
	'Theft':'Robo',
	'Thermal Capture':'Captura térmica',
	'Time Bubbles':'Burbujas de tiempo',
	'Time Threads':'Hilos temporales',
	'Ultraviolet Radiation':'Radiación ultravioleta',
	'Underground Bubbles':'Burbujas subterráneas',
	'Algal particulates': 'Partículas de algas',
	'Coral Microcolony':'Microcolonia de coral',
	'Ensnares Fish':'Atrapa peces',
	'Feeds on Failure':'Transmisiones de fracasos',
	'Hydrosynthesis':'Hidrosíntesis',
	'Mineral Filtration':'Filtrado de minerales',
	'Oxygen Filtration':'Filtrado de oxígeno',
	'Plankton Symbiotes':'Simbiontes de plancton',
	'Plankton':'Plancton',
	'Salt Absorption':'Absorción de sal',
	'Vented minerals':'Minerales agujereados',
};

export default floranutSourceDatalist;
