/**
 * @fileoverview Provides data for flora datalists
 */
  const florarootDatalist:
  { [key: string]: string
  } = {
		'Complex':'Compleja',
		'Fractal':'Fractal',
		'Widespread':'Extendida',
		'Stunted':'Atrofiada',
		'Swamped':'Inundada',
		'Desiccated':'Desecada',
		'Extensive':'Extensa',
		'Concentrated':'Concentrada',
		'Symbiotic':'Simbiótica',
		'Fungal':'Fúngica',
		'Localised':'Localizada',
		'Bi-directional':'Bidireccional',
		'Many-Limbed':'Multirradicular',
		'Gravitational':'Gravitacional',
		'Unsupported':'Sin sujeción',
		'Inorganic':'Inorgánica',
		'Significant':'Considerable',
		'Efficient':'Eficaz',
		'Far Reaching':'De largo alcance',
		'Capacious':'Grande',
		'Limited':'Limitada',
		'Narrow':'Estrecha',
		'Restricted':'Restringida',
		'Parasitic':'Parasitaria',
		'Invasive':'Invasiva',
		'Extendable':'Extensible',
		'Voluminous':'Voluminosa',
		'Global':'Global',
		'Knotted':'Anudada',
		'Linear':'Lineal',
		'Branching':'Ramificada',
		'Substantial':'Sólida',
		'Conventional':'Convencional',
		'Circular':'Circular',
		'Independent':'Independiente',
		'Sentient':'Sensible',
		'Heat Seeking':'Termodirigida',
		'Simple':'Simple',
		'Regular':'Regular',
		'Polygonal':'Poligonal',
		'Not Present':'Ausente',
		'Hidden':'Impenetrable',
		'Balanced':'Equilibrada',
		'Omni-Directional':'Omnidireccional',
		'Irregular':'Irregular',
		'Transferrable':'Transferible',
		'Mobile':'Móvil',
		'Obtuse':'Obtusa',
		'Unfathomable':'Insondable',
		'Grasping':'Agarradiza',
  };
export default florarootDatalist;