/**
 * @fileoverview Provides data for mineral datalists
 */

const mineralNotesDatalist: {
  [key: string]: string
  } = {
    'Extreme Salt Content':'Contenido en sal extremo',
    'High Surface Temperature':'Temperatura superficial elevada',
    'Audiophobic':'Audiofóbico',
    'Hydrophobic':'Hidrofóbico',
    'Liquid Centre':'Centro líquido',
    'Slow Moving':'De movimiento lento',
    'High Viscosity':'Viscosidad elevada',
    'Molten Core':'Núcleo fundido',
    'Frozen in Time':'Congelado en el tiempo',
    'Fragile Crust':'Corteza frágil',
    'Toxic Dust':'Polvo tóxico',
    'Ancient':'Ancestral',
    'Slow-Forming':'De formación lenta',
    'Unnaturally Sculpted':'Esculpido extrañamente',
    'Radioactive':'Radiactivo',
    'Shatter Resistant':'Resistente a la fractura',
    'Porous':'Poroso',
    'Unusually Soft':'Inusualmente blando',
    'Strong Odour':'Olor fuerte',
    'Sulphurous':'Sulfuroso',
    'Faintly Luminous':'Ligeramente luminoso',
    'Hard Wearing':'Resistente',
    'High Density':'Alta densidad',
    'Buoyant':'Flotante',
    'Silicate':'Silicato',
    'Extrusive':'Extrusivo',
    'Abrasive':'Abrasivo',
    'Pyroclastic':'Piroclástico',
    'Feldspar':'Feldespato',
    'Quasi-Ferrous':'Cuasi-ferroso',
    'Igneous':'Ígneo',
    'Exfoliating':'Exfoliante',
    'High Phosphate':'Alto fosfato',
    'Low Specific Gravity':'Gravedad específica baja',
    'Superconductive':'Superconductor',
    'Quantum Instability':'Inestabilidad cuántica',
    'Vacuum Core':'Núcleo de vacío',
    'Musical When Struck':'Musical al golpearlo',
    'Inedible':'No comestible',
    'Soft':'Blando',
    'Unexpectedly Buoyant':'Inesperadamente flotante',
    'Elastic':'Elástico',
    'Biologically Active':'Biológicamente activo',
    'Parasite Host':'Huésped de parásitos',
    'Polyp Colony':'Colonia de pólipos',
    'Partially Invisible':'Parcialmente invisible',
    'Quartz Core':'Núcleo de cuarzo',
    'Complex Crystals':'Cristales complejos',
    'Electromagnetic':'Electromagnético',
    'Gravitational Bonds':'Conexiones gravitacionales',
    'Potentially Synthetic':'Potencialmente sintético',
    'Infested':'Infestado',
    'Mimic':'Mímico',
    'Inert':'Inerte',
    'Eroded':'Erosionado',
    'Durable':'Duradero',
    'Geode Rich':'Rico en geodas',
    'Conductive':'Conductor',
    'Recently Formed':'Recientemente formado',
    'Industrially Valuable':'Valioso para la industria',
    'Bonelike':'Aspecto óseo',
    'Water Resistant':'Resistente al agua',
    'Oily Coating':'Cubierta aceitosa',
    'Artificial':'Artificial',
    'Misleading Structure':'Estructura engañosa',
    'Potentially Explosive':'Potencialmente explosivo',
    'Multi-Layered':'Multicapa',
    'Contains Dark Matter':'Contiene materia oscura',
    'Contains Water':'Contiene agua',
    'Contains Organic Matter':'Contiene materia orgánica',
    'Faint Life Signs':'Signos vitales débiles',
    'Moss Habitat':'Hábitat musgoso',
    'Frozen Centre':'Centro congelado',
    'Melts Easily':'Fácilmente fundible',
    'Powerful Heat Source':'Fuente de calor potente',
    'Mollusc Habitat':'Hábitat de moluscos',
    'Nutrient Rich':'Rico en nutrientes',
    'Yeast Colony':'Colonia de levaduras',
    'Proto Cellular Structure':'Estructura protocelular',
};

export default mineralNotesDatalist;

