/**
 * @fileoverview Provides data for mineral datalists
 */
const mineralDatalists = {
  formationData: [
    'Soil Compaction',
    'Water Transport',
    'Atmospheric Metal',
    'Plant Deposits',
    'Living Stone',
    'Evaporation',
    'Wind Erosion',
    'Gravitational',
    'Volcanic',
    'High-Pressure',
    'Gas Humidity',
    'Sublimation',
    'Calcified Fauna',
    'Salt Bonding',
    'Low Energy Reaction',
    'Magnetic Attraction',
    'Reductive Boiling',
    'Salt Baked',
    'Soil Amalgamation',
    'Ancient Tidal Erosion',
    'Metamorphic',
    'Polymerisation',
    'Coalescence',
    'Slow Drips',
    'Photonic',
    'Ground up Shells',
    'Old Bones',
    'Tectonic',
    'Spontaneous',
    'Calcium Secretion',
    'Hydrothermal',
    'Vented Minerals',
    'Explosive Magma',
    'Pyroclastic',
    'Jet Pressure',
    'Gas Bubbles',
    'Diagenesis',
    'Metal Vapour',
    'Ammonia Groundwater',
    'Lithification',
    'Cementation',
    'Bedrock Expulsion',
    'Petrifaction',
    'Fossilisation',
    'Sedimentation',
    'Celestial',
    'Meteorite Impact',
    'Localised Black Hole',
    'Comet Fragment',
    'Animal Deposits',
  ],
  mineralNotesData: [
    'Extreme Salt Content',
    'High Surface Temperature',
    'Audiophobic',
    'Hydrophobic',
    'Liquid Centre',
    'Slow Moving',
    'High Viscosity',
    'Molten Core',
    'Frozen in Time',
    'Fragile Crust',
    'Toxic Dust',
    'Ancient',
    'Slow-Forming',
    'Unnaturally Sculpted',
    'Radioactive',
    'Shatter Resistant',
    'Porous',
    'Unusually Soft',
    'Strong Odour',
    'Sulphurous',
    'Faintly Luminous',
    'Hard Wearing',
    'High Density',
    'Buoyant',
    'Silicate',
    'Extrusive',
    'Abrasive',
    'Pyroclastic',
    'Feldspar',
    'Quasi-Ferrous',
    'Igneous',
    'Exfoliating',
    'High Phosphate',
    'Low Specific Gravity',
    'Superconductive',
    'Quantum Instability',
    'Vacuum Core',
    'Musical When Struck',
    'Inedible',
    'Soft',
    'Unexpectedly Buoyant',
    'Elastic',
    'Biologically Active',
    'Parasite Host',
    'Polyp Colony',
    'Partially Invisible',
    'Quartz Core',
    'Complex Crystals',
    'Electromagnetic',
    'Gravitational Bonds',
    'Potentially Synthetic',
    'Infested',
    'Mimic',
    'Inert',
    'Eroded',
    'Durable',
    'Geode Rich',
    'Conductive',
    'Recently Formed',
    'Industrially Valuable',
    'Bonelike',
    'Water Resistant',
    'Oily Coating',
    'Artificial',
    'Misleading Structure',
    'Potentially Explosive',
    'Multi-Layered',
    'Contains Dark Matter',
    'Contains Water',
    'Contains Organic Matter',
    'Faint Life Signs',
    'Moss Habitat',
    'Frozen Centre',
    'Melts Easily',
    'Powerful Heat Source',
    'Mollusc Habitat',
    'Nutrient Rich',
    'Yeast Colony',
    'Proto Cellular Structure',
  ],
  mineralResources: [
    '',
    'Ferrite Dust',
    'Pure Ferrite',
    'Di-hydrogen',
    'Chromatic Metal',
    'Sodium',
    'Oxygen',
    'Cobalt',
    'Salt',
    'Chlorine',
    'Ionised Cobalt',
    'Copper',
    'Silver',
    'Tritium',
    'Carbon',
  ],
};

export default mineralDatalists;
