function startupFunctions(){wormName(),catalogue(),autoSpawn(),albumFunctions()}const sandwormElements={input:{autoSpawn:"autoSpawnInput"}},sandwormElementFunctions=(updateGlobalElements(sandwormElements),{civ:["catalogue(); albumItemType()",null,!0],planetInput:["wormName(); planetMoonSentence(); albumName()"],moonInput:["wormName(); planetMoonSentence(); albumName()"],autoSpawn:["autoSpawn()"],researchTeam:["catalogue()",null,!0],wormclassInput:["albumName()"],wormmaxdepthInput:["numberStats(this, 1); albumOther()"],discoveredInput:["albumDiscoverer()"],discoveredlinkInput:["albumDiscoverer()"]});function wormName(){const a=pageData.planet,e=pageData.moon;var n;a?(n=e||a,wikiCode(n,"bodyName"),pageData.name="Immortal Worm "+n):pageData.name=""}function autoSpawn(){var a=(()=>{for(const a of globalElements.input.autoSpawn)if(a.checked)return a.value})(),e=`This creature ${a} automatically spawn on game reload`;a?(globalElements.output.autoSpawn.style.display="",globalElements.output.autoSpawn.innerText=e):globalElements.output.autoSpawn.style.display="none",addInfoBullet()}function catalogue(){var a=docByResearchteam("GHEC"),e=(()=>{switch(pageData.civShort){case"GHub":return"GHEC Sandworm";case"CalHub":return"CalHub Rare Fauna Album#Sandworm|CalHub Rare Fauna";case"EisHub":return"EisHub Shaihuluda"}})()+" Album";wikiCode(`[[${e}]]`+a,"addInfo"),addInfoBullet(),pageData.catalogue=e}function albumItemTypeExternal(){return pageData.catalogue.split("|").at(-1)}function albumCivExternal(){return""}function albumNameExternal(){return enableTextMarking(),pageData.name+"|"+pageData.wormclass}function albumOtherExternal(){return`(${pageData.wormmaxdepth}ku)`}function albumLinkGen(){return pageData.catalogue.split("|")[0]}function generateGalleryArray(){var a,e=["","Worm scan","Moon Page","Planet Page","System Page","Galaxy Map"];pageData.moon||(a=e.findIndex(a=>a.toLowerCase().includes("moon")),e.splice(a,1)),pageData.galleryArray=e}function galleryExplanationExternal(){return`The preferred order of pictures is as follows:
	<div class='dialog-center'>
		<ol class='dialog-list'>
			<li>Worm scan</li>
			<li>Moon Page</li>
			<li>Planet Page</li>
			<li>System Page</li>
			<li>Galaxy Map</li>
		</ol>
	</div>`}assignElementFunctions(sandwormElementFunctions);