name: Generate JSDocs
run-name: Generate Documentation

on:
  push:
    branches: ['main']

concurrency:
  group: "doc"
  cancel-in-progress: true

jobs:
  Create:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Doc
        uses: Lenni009/jsdoc2wiki-action/create-doc@main