name: Lint JSDoc
run-name: Lint JSDoc Comments

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: "lintdoc"
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Lint JSDoc Comments
        uses: Lenni009/jsdoc2wiki-action/lint-doc@main