import type { SelectOption } from '@/types/selectInputOptions';

const InEnglish = [
  '',
  'Asynchronous',
  'Circular',
  'Electronic',
  'Mutable',
  'Non-boolean',
  'Non-Euclidean',
  'Uninitialised',
  'Unmeasurable',
  'Virtual',
  'Alpha',
  'Asymmetric',
  'Asymptotic',
  'Exotic',
  'Female',
  'Non-uniform',
  'None',
  'Orthogonal',
  'Prime',
  'Radical',
  'Rational',
  'Symmetric',
  'Unknown',
  'Vectorised',
] as const;

// const InSpanish = [
//   '',
//   'Asíncrono',
//   'Circular',
//   'Electrónico',
//   'Mutable',
//   'No booleano',
//   'No euclidiano',
//   'No inicializado',
//   'Inmensurable',
//   'Virtual',
//   'Alfa',
//   'Asimétrico',
//   'Asintótico',
//   'Exótico',
//   'Hembra',
//   'No uniforme',
//   'Ninguno',
//   'Ortogonal',
//   'Principal',
//   'Radical',
//   'Racional',
//   'Simétrico',
//   'Desconocido',
//   'Vectorizado',
// ] as const;

export const mappedModeOptions: SelectOption[] = InEnglish.map((InEnglish) => ({ label: InEnglish, value: InEnglish }));
