(() => {
	const systemDatalists = {
		terminal: [
			'Decrypted User Data',
			'Star Silk',
			'Comet Droplets',
			'Ion Sphere',
			'Decrypted User Data',
			'Teleport Coordinators',
			'Nanotube Crate',
			'Self-Repairing Heridium',
			'Optical Solvent',
			'5D Torus',
			'Superconducting Fibre',
			'De-Scented Bottles',
			'Neutron Microscope',
			'Instability Injector',
			'Organic Piping',
			'Neural Duct',
			'Dirt',
			'Unrefined Pyrite Grease',
			'Bromide Salt',
			'Polychromatic Zirconium',
			'Re-latticed Arc Crystal',
			'Enormous Metal Cog',
			'Non-Stick Piston',
			'Mesh Decouplers',
			'Holographic Crankshaft',
			'Vector Compressors',
			'Decommissioned Circuits',
			'Welding Soap',
			'Ion Capacitor',
			'Autonomous Positioning Unit',
			'Quantum Accelerator',
			'Spark Canister',
			'Industrial-Grade Battery',
			'Ohmic Gel',
			'Experimental Power Fluid',
			'Fusion Core'
		],
		resources: [
			'Copper',
			'Cadmium',
			'Emeril',
			'Indium',
			'Activated Copper',
			'Activated Cadmium',
			'Activated Emeril',
			'Activated Indium',
			'Ammonia',
			'Dioxite',
			'Paraffinium',
			'Phosphorus',
			'Pyrite',
			'Uranium',
			'Silver',
			'Gold',
			'Magnetised Ferrite',
			'Sodium',
			'Cobalt',
			'Salt',
			'Star Bulb',
			'Cactus Flesh',
			'Gamma Root',
			'Fungal Mould',
			'Frost Crystal',
			'Solanium',
			'Mordite',
			'Faecium',
			'Ancient Bones',
			'Salvageable Scrap'
		]
	}
	datalists(systemDatalists);
})();